// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PetAdmissionDate");

                    b.Property<string>("PetBreed");

                    b.Property<string>("PetDescription");

                    b.Property<string>("PetName");

                    b.Property<string>("PetTaxonomy");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            PetAdmissionDate = "8/13/2020",
                            PetBreed = "Calico",
                            PetDescription = "Don't look Mark straight in the eyes. He likes to get scratchy.",
                            PetName = "Mark",
                            PetTaxonomy = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
